name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install valgrind 
      run: sudo apt-get -y install valgrind
    - name: make test
      run: |
        make test -C Implementation/
        valgrind ./Implementation/build/Test_calculator.out
